**A. REPRODUCIBLE NORMALIZATION PROBLEM**


In [2]:
import numpy as np

In [4]:
np.random.seed(2112)

In [3]:
x = np.random.randint(10, 101, size=(5, 5))
x

array([[48, 76, 53, 27, 70],
       [36, 62, 51, 51, 20],
       [51, 10, 20, 63, 68],
       [70, 37, 36, 25, 44],
       [66, 25, 82, 43, 64]])

In [6]:
X_mean = x.mean()
X_mean

np.float64(47.92)

In [9]:
X_std = x.std()
X_std

np.float64(19.30993526659269)

In [10]:
X_normalized = (x- X_mean)/X_std
X_normalized

array([[ 0.00414295,  1.4541737 ,  0.26307701, -1.08338012,  1.14345282],
       [-0.61729881,  0.72915832,  0.15950338,  0.15950338, -1.44588781],
       [ 0.15950338, -1.96375594, -1.44588781,  0.78094513,  1.0398792 ],
       [ 1.14345282, -0.56551199, -0.61729881, -1.18695375, -0.20300431],
       [ 0.93630557, -1.18695375,  1.76489458, -0.25479112,  0.83273195]])

In [12]:
print ("Original Array (x):", x)
print ("X_normalized:", X_normalized)
print ("X_normalized mean:", X_normalized.mean())
print ("X_normalized standard deviation:", X_normalized.std())

Original Array (x): [[48 76 53 27 70]
 [36 62 51 51 20]
 [51 10 20 63 68]
 [70 37 36 25 44]
 [66 25 82 43 64]]
X_normalized: [[ 0.00414295  1.4541737   0.26307701 -1.08338012  1.14345282]
 [-0.61729881  0.72915832  0.15950338  0.15950338 -1.44588781]
 [ 0.15950338 -1.96375594 -1.44588781  0.78094513  1.0398792 ]
 [ 1.14345282 -0.56551199 -0.61729881 -1.18695375 -0.20300431]
 [ 0.93630557 -1.18695375  1.76489458 -0.25479112  0.83273195]]
X_normalized mean: -1.2878587085651815e-16
X_normalized standard deviation: 0.9999999999999999


In [17]:
np.save("X_normalized.npy", X_normalized)


**B. CUBES DIVISIBLE BY 4 PROBLEM**

In [14]:
c = (np.arange(1, 101)**3).reshape(10,10)
c

array([[      1,       8,      27,      64,     125,     216,     343,
            512,     729,    1000],
       [   1331,    1728,    2197,    2744,    3375,    4096,    4913,
           5832,    6859,    8000],
       [   9261,   10648,   12167,   13824,   15625,   17576,   19683,
          21952,   24389,   27000],
       [  29791,   32768,   35937,   39304,   42875,   46656,   50653,
          54872,   59319,   64000],
       [  68921,   74088,   79507,   85184,   91125,   97336,  103823,
         110592,  117649,  125000],
       [ 132651,  140608,  148877,  157464,  166375,  175616,  185193,
         195112,  205379,  216000],
       [ 226981,  238328,  250047,  262144,  274625,  287496,  300763,
         314432,  328509,  343000],
       [ 357911,  373248,  389017,  405224,  421875,  438976,  456533,
         474552,  493039,  512000],
       [ 531441,  551368,  571787,  592704,  614125,  636056,  658503,
         681472,  704969,  729000],
       [ 753571,  778688,  804357,  8

In [20]:
div_by_4 = c[c % 4 == 0]
div_by_4

array([      8,      64,     216,     512,    1000,    1728,    2744,
          4096,    5832,    8000,   10648,   13824,   17576,   21952,
         27000,   32768,   39304,   46656,   54872,   64000,   74088,
         85184,   97336,  110592,  125000,  140608,  157464,  175616,
        195112,  216000,  238328,  262144,  287496,  314432,  343000,
        373248,  405224,  438976,  474552,  512000,  551368,  592704,
        636056,  681472,  729000,  778688,  830584,  884736,  941192,
       1000000])

In [21]:
print ("Shape of C:", c.shape)
print ("Array div_by_4:", div_by_4)
print ("Number of selected elements:", len(div_by_4))

Shape of C: (10, 10)
Array div_by_4: [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]
Number of selected elements: 50


In [22]:
np.save("div_by_4", div_by_4)

**C. ABOVE-MEAN SQUARES PROBLEM**

In [24]:
S = (np.arange(1, 37)**2).reshape(6,6)
S

array([[   1,    4,    9,   16,   25,   36],
       [  49,   64,   81,  100,  121,  144],
       [ 169,  196,  225,  256,  289,  324],
       [ 361,  400,  441,  484,  529,  576],
       [ 625,  676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225, 1296]])

In [25]:
S_mean = S.mean()
S_mean

np.float64(450.1666666666667)

In [26]:
above_mean = S[S > S_mean]
above_mean

array([ 484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296])

In [27]:
print ("S:", S)
print ("S_mean:", S_mean)
print ("S above mean:", above_mean)
print ("Number of selected elements:", len(above_mean))

S: [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]
S_mean: 450.1666666666667
S above mean: [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]
Number of selected elements: 15


In [28]:
np.save("above_mean.npy", above_mean)